# Problem Statement
- In this i will make custom linear regression mean i will make my own class

# Import Packages

In [1]:
import pandas as pd
import numpy as np

# Custom Class

In [133]:
class MyLR:
    def __init__(self):
        self.m=None
        self.b=None
    
    def fit(self,x_train,x_test):
        num=0
        dnum=0

        for i in range(x_train.shape[0]):
            num=num+((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            dnum=dnum+((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))
            
        self.m=num/dnum
        self.b=y_train.mean()-self.m*x_train.mean()
        return self.m,self.b
    def predict(self,x_test):
        y=self.m*x_test+self.b
        
        return y
    

# Laod Dataset

In [134]:
df=pd.read_csv("placement-dataset.csv",usecols=['cgpa','iq'])
df.head(3)

cgpa     iq
0   6.8  123.0
1   5.9  106.0
2   NaN  121.0

In [135]:
df.dropna(inplace=True)

In [136]:
from sklearn.model_selection import train_test_split

In [137]:
X=df['iq'].values
y=df['cgpa'].values

In [138]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [139]:
x_train.shape

(70,)

In [140]:
lr=MyLR()

In [141]:
lr.fit(x_train,y_train)

(-0.004253581862335432, 6.538204302351227)

In [142]:
lr.predict(x_test.reshape(-1,1))

array([[5.9767315 ],
       [6.01501373],
       [5.94695642],
       [6.01076015],
       [5.78957389],
       [6.32552521],
       [5.94695642],
       [6.02777448],
       [6.33403237],
       [6.19366417],
       [5.7640524 ],
       [5.81934897],
       [6.10433895],
       [6.0703103 ],
       [6.35955386],
       [5.8831527 ],
       [5.91718135],
       [5.86613837]])

In [143]:
from sklearn.linear_model import LinearRegression

In [144]:
model=LinearRegression()

In [145]:
model.fit(x_train.reshape(-1,1),y_train.reshape(-1,1))

LinearRegression()

In [146]:
model.predict(x_test.reshape(-1,1))

array([[5.9767315 ],
       [6.01501373],
       [5.94695642],
       [6.01076015],
       [5.78957389],
       [6.32552521],
       [5.94695642],
       [6.02777448],
       [6.33403237],
       [6.19366417],
       [5.7640524 ],
       [5.81934897],
       [6.10433895],
       [6.0703103 ],
       [6.35955386],
       [5.8831527 ],
       [5.91718135],
       [5.86613837]])

In [147]:
model.coef_

array([[-0.00425358]])

In [148]:
model.intercept_

array([6.5382043])

# Conclussion
- We see that both our class and sklearn class give same results