# Statement
- **In this file i will make a custom linear multiple regression class**

In [3]:
import pandas as pd
import numpy as np

# Load the dataset

In [21]:
from sklearn.datasets import load_diabetes

In [25]:
data=load_diabetes()
X=data.data
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [27]:
y=data.target
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

# Split the data

In [11]:
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=43)

In [29]:
x_train.shape

(353, 10)

# Apply Sklearn Linear Regression

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
lr=LinearRegression()

In [34]:
lr.fit(x_train,y_train)

LinearRegression()

In [36]:
pre=lr.predict(x_test)

In [37]:
from sklearn.metrics import r2_score

In [38]:
r2_score(y_test,pre)

0.5419836643066976

In [39]:
lr.coef_

array([ -60.39984809, -226.08359044,  529.38495719,  259.96199412,
       -859.09300933,  504.68697339,  157.41085788,  226.29313436,
        840.7840406 ,   34.71226556])

In [40]:
lr.intercept_

152.0532454782767

# Make own Class
- **θ=(X T X)^−1(X T y)**

- **Steps**
    - First add n nbr of 1 in the x_train.
    - Calculate the Cofficent

In [82]:
class MLR:
    def __init__(self):
        self.coff_=None
        self.intersept=None
    
    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        
        x_transpose=x_train.transpose()
        
        x_transpose_x=np.dot(x_transpose,x_train)
        
        x_transpose_inv=np.linalg.inv(x_transpose_x)
        
        x_transpose_y=np.dot(x_transpose,y_train)
        
        betas=np.dot(x_transpose_inv,x_transpose_y)
       
        self.coff_=betas[1:]
        self.intersept=betas[0]
    def predict(self,x_test):
        pass

In [83]:
l=MLR()

In [84]:
l.fit(x_train,y_train)

In [86]:
l.coff_

array([ -60.39984809, -226.08359044,  529.38495719,  259.96199412,
       -859.09300933,  504.68697339,  157.41085788,  226.29313436,
        840.7840406 ,   34.71226556])

In [87]:
l.intersept

152.0532454782767

# Conclussion
- We can see that both `our` class and `sklearn` class both are the same results.