# import packages

In [18]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
import warnings
warnings.filterwarnings('ignore')

# Laod Dataset

In [2]:
data=load_breast_cancer()

In [5]:
feature=data.data
target=data.target

In [6]:
feature

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [7]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

# Tarin Test Split

In [14]:
from  sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV

In [9]:
x_train,x_test,y_train,y_test=train_test_split(feature,target,test_size=0.2,random_state=43)

In [10]:
x_train

array([[1.189e+01, 2.117e+01, 7.639e+01, ..., 8.263e-02, 3.075e-01,
        7.351e-02],
       [1.955e+01, 2.877e+01, 1.336e+02, ..., 1.941e-01, 2.818e-01,
        1.005e-01],
       [1.157e+01, 1.904e+01, 7.420e+01, ..., 6.664e-02, 3.035e-01,
        8.284e-02],
       ...,
       [1.881e+01, 1.998e+01, 1.209e+02, ..., 1.294e-01, 2.567e-01,
        5.737e-02],
       [1.396e+01, 1.705e+01, 9.143e+01, ..., 1.374e-01, 3.068e-01,
        7.957e-02],
       [1.025e+01, 1.618e+01, 6.652e+01, ..., 9.744e-02, 2.608e-01,
        9.702e-02]])

In [11]:
x_test

array([[1.324e+01, 2.013e+01, 8.687e+01, ..., 1.357e-01, 2.845e-01,
        1.249e-01],
       [1.120e+01, 2.937e+01, 7.067e+01, ..., 0.000e+00, 1.566e-01,
        5.905e-02],
       [1.674e+01, 2.159e+01, 1.101e+02, ..., 1.813e-01, 4.863e-01,
        8.633e-02],
       ...,
       [1.378e+01, 1.579e+01, 8.837e+01, ..., 3.312e-02, 1.859e-01,
        6.810e-02],
       [8.888e+00, 1.464e+01, 5.879e+01, ..., 4.786e-02, 2.254e-01,
        1.084e-01],
       [1.404e+01, 1.598e+01, 8.978e+01, ..., 7.453e-02, 2.725e-01,
        7.234e-02]])

# import models

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [16]:
lr=LogisticRegression()
dt=DecisionTreeClassifier()
knn=KNeighborsClassifier()

In [17]:
lr_score=cross_val_score(lr,x_train,y_train,cv=5,scoring='accuracy',n_jobs=-1,verbose=1).mean()
dt_score=cross_val_score(dt,x_train,y_train,cv=5,scoring='accuracy',n_jobs=-1,verbose=1).mean()
knn_score=cross_val_score(knn,x_train,y_train,cv=5,scoring='accuracy',n_jobs=-1,verbose=1).mean()

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    4.6s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.2s finished


In [19]:
print(f"LogisticRegression Score: {lr_score}")
print(f"DecessionTree Score: {dt_score}")
print(f"KNN Score: {knn_score}")

LogisticRegression Score: 0.9384615384615385
DecessionTree Score: 0.9164835164835166
KNN Score: 0.9120879120879122


**we can see that we can get best result at `LogisticRegression`**

# Apply bagging

In [20]:
from sklearn.ensemble import BaggingClassifier

**Estimator with `LogisticRegression`**

In [21]:
bag1=BaggingClassifier(estimator=lr)
cross_val_score(bag1,x_train,y_train,cv=5,scoring='accuracy',n_jobs=-1,verbose=1).mean()

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.8s finished


0.9406593406593406

**With `DecessionTree`**

In [22]:
bag2=BaggingClassifier(estimator=dt)
cross_val_score(bag2,x_train,y_train,cv=5,scoring='accuracy',n_jobs=-1,verbose=1).mean()

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.4s finished


0.9494505494505494

**With KNN**

In [23]:
bag3=BaggingClassifier(estimator=knn)
cross_val_score(bag3,x_train,y_train,cv=5,scoring='accuracy',n_jobs=-1,verbose=1).mean()

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    0.9s finished


0.90989010989011

# Now Apply Hyperparameter Tunning

In [24]:
param={
    'base_estimator':[lr,dt,knn],
    'n_estimators':[10,20,30,50],
    'max_samples':[0.5,0.75,1.0],
    'max_features':[0.5,1.0],
    'bootstrap':[True,False],
    'bootstrap_features':[True,False],
    'oob_score':[True,False],
}

In [25]:
bag=BaggingClassifier()
grid_search=GridSearchCV(estimator=bag,param_grid=param,n_jobs=-1,verbose=1,cv=5,scoring='accuracy')
grid_search

GridSearchCV(cv=5, estimator=BaggingClassifier(), n_jobs=-1,
             param_grid={'base_estimator': [LogisticRegression(),
                                            DecisionTreeClassifier(),
                                            KNeighborsClassifier()],
                         'bootstrap': [True, False],
                         'bootstrap_features': [True, False],
                         'max_features': [0.5, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [10, 20, 30, 50],
                         'oob_score': [True, False]},
             scoring='accuracy', verbose=1)

In [28]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 576 candidates, totalling 2880 fits


GridSearchCV(cv=5, estimator=BaggingClassifier(), n_jobs=-1,
             param_grid={'base_estimator': [LogisticRegression(),
                                            DecisionTreeClassifier(),
                                            KNeighborsClassifier()],
                         'bootstrap': [True, False],
                         'bootstrap_features': [True, False],
                         'max_features': [0.5, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [10, 20, 30, 50],
                         'oob_score': [True, False]},
             scoring='accuracy', verbose=1)

In [29]:
print(f"best parametre are {grid_search.best_params_}")

best parametre are {'base_estimator': DecisionTreeClassifier(), 'bootstrap': True, 'bootstrap_features': False, 'max_features': 1.0, 'max_samples': 1.0, 'n_estimators': 50, 'oob_score': True}


In [30]:
print(f"best score is {grid_search.best_score_:.4f}")

best score is 0.9626


**We can see we can get `96%` score at some parameter** 

In [31]:
final=BaggingClassifier(base_estimator=dt,bootstrap=True,bootstrap_features=False,max_features=1.0,max_samples=1.0,n_estimators=50,oob_score=True)
final

BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=50,
                  oob_score=True)

In [32]:
final.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=50,
                  oob_score=True)

In [33]:
pre=final.predict(x_test)

In [34]:
accuracy_score(y_test,pre)

0.9736842105263158